### ISSUE TITLE
Remove the Image tool

### ISSUE THREAD

**Issue by ChristopherChudzicki** [mitodl/ocw-studio#1480]
### Steps to Reproduce

1. Open any studio page for editing. For example, any page at https://ocw-studio-rc.odl.mit.edu/sites/wgs-s10-special-topics-in-women-gender-studies-seminar-latina-womens-voices-spring-2010/type/page/ _Seems not to happen with direct links, so click on any page there._

### Expected Behavior

No console errors

### Actual Behavior

Console error
```
ckeditor.js:5 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'destroy')
    at Ot._destructor (ckeditor.js:5:20995)
    at ckeditor.js:5:22255
```

**Comment by ChristopherChudzicki** [comment]
This error seems to be coming from our CKEditor config: This error seems to be eminating from https://github.com/mitodl/ocw-studio/blob/0c9549737d69c5783d7c646aa2a0d67a63baaf70/static/js/lib/ckeditor/CKEditor.ts#L112-L114

The imageStyle stuff is for CKEditor's image plugin. The image toolbar is a mini-toolbar that provides options about styling the image. But... We do not actually use that plugin. (We load it, but we do not display the main toolbar that enables it.) Maybe we used to? I'm not sure.

Additionally, we are on CKEditor 30 (iirc) and `imageStyle:full` was removed in 29. 

Related: https://github.com/ckeditor/ckeditor5/issues/11090#issuecomment-1018632963
