### ISSUE TITLE
Fix flaky JS test (SingletonsContentListing)

### ISSUE THREAD

**Issue by gsidebo** [mitodl/ocw-studio#269]
This JS test failed during the build for a backend-only PR

```
FAIL static/js/components/SingletonsContentListing.test.tsx
  ● SingletonsContentListing › loads content detail from the API if needed

    AssertError: expected stub to be called once but was called 0 times

      165 |       tabLink.prop("onClick")({ preventDefault: helper.sandbox.stub() })
      166 |     })
    > 167 |     sinon.assert.calledOnce(contentDetailStub)
          |                  ^
      168 |   })
      169 |
      170 |   it("should render the SiteContentEditor component", async () => {

      at Object.fail (node_modules/sinon/lib/sinon/assert.js:110:25)
      at failAssertion (node_modules/sinon/lib/sinon/assert.js:67:20)
      at Object.assert.<computed> [as calledOnce] (node_modules/sinon/lib/sinon/assert.js:93:17)
      at static/js/components/SingletonsContentListing.test.tsx:167:18
      at fulfilled (static/js/components/SingletonsContentListing.test.tsx:5:58)
```

**Comment by mbertrand** [comment]
Failed again today
