### ISSUE TITLE
ForeignKeyViolation when importing courses on RC

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ocw-studio#540]
### Steps to Reproduce
Run `./manage.py import_ocw_course_sites -b ocw-to-hugo-output-qa`

I'm seeing frequent exceptions in the logs:

    2021-09-01T18:47:22.332974+00:00 app[worker.1]: [2021-09-01 18:47:22,332: ERROR/ForkPoolWorker-9] Task ocw_import.tasks.import_ocw2hugo_course_paths[a9a17acb-45f0-40eb-a1a2-0fbf11423f16] raised unexpected: IntegrityError('update or delete on table "websites_websitecontent" violates foreign key constraint "websites_websitecont_parent_id_3eb76791_fk_websites_" on table "websites_websitecontent"\nDETAIL:  Key (id)=(250589) is still referenced from table "websites_websitecontent".\n')
    2021-09-01T18:47:22.332976+00:00 app[worker.1]: Traceback (most recent call last):
    2021-09-01T18:47:22.332977+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    2021-09-01T18:47:22.332977+00:00 app[worker.1]: return self.connection.commit()
    2021-09-01T18:47:22.332978+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/database_dbapi2.py", line 89, in commit
    2021-09-01T18:47:22.332978+00:00 app[worker.1]: return self.__wrapped__.commit()
    2021-09-01T18:47:22.332979+00:00 app[worker.1]: psycopg2.errors.ForeignKeyViolation: update or delete on table "websites_websitecontent" violates foreign key constraint "websites_websitecont_parent_id_3eb76791_fk_websites_" on table "websites_websitecontent"
    2021-09-01T18:47:22.332980+00:00 app[worker.1]: DETAIL:  Key (id)=(250589) is still referenced from table "websites_websitecontent".
    2021-09-01T18:47:22.332981+00:00 app[worker.1]: 
    2021-09-01T18:47:22.332981+00:00 app[worker.1]: 
    2021-09-01T18:47:22.332982+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
    2021-09-01T18:47:22.332982+00:00 app[worker.1]: 
    2021-09-01T18:47:22.332982+00:00 app[worker.1]: Traceback (most recent call last):
    2021-09-01T18:47:22.332982+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    2021-09-01T18:47:22.332983+00:00 app[worker.1]: R = retval = fun(*args, **kwargs)
    2021-09-01T18:47:22.332983+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/application_celery.py", line 99, in wrapper
    2021-09-01T18:47:22.332984+00:00 app[worker.1]: return wrapped(*args, **kwargs)
    2021-09-01T18:47:22.332984+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    2021-09-01T18:47:22.332984+00:00 app[worker.1]: return self.run(*args, **kwargs)
    2021-09-01T18:47:22.332985+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 171, in _inner
    2021-09-01T18:47:22.332985+00:00 app[worker.1]: reraise(*exc_info)
    2021-09-01T18:47:22.332986+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 57, in reraise
    2021-09-01T18:47:22.332986+00:00 app[worker.1]: raise value
    2021-09-01T18:47:22.332986+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/sentry_sdk/integrations/celery.py", line 166, in _inner
    2021-09-01T18:47:22.332986+00:00 app[worker.1]: return f(*args, **kwargs)
    2021-09-01T18:47:22.332987+00:00 app[worker.1]: File "/app/ocw_import/tasks.py", line 47, in import_ocw2hugo_course_paths
    2021-09-01T18:47:22.332987+00:00 app[worker.1]: delete_unpublished_courses(paths, filter_str)
    2021-09-01T18:47:22.332988+00:00 app[worker.1]: File "/app/ocw_import/api.py", line 373, in delete_unpublished_courses
    2021-09-01T18:47:22.332988+00:00 app[worker.1]: unpublished_courses.delete()
    2021-09-01T18:47:22.332988+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/db/models/query.py", line 747, in delete
    2021-09-01T18:47:22.332989+00:00 app[worker.1]: deleted, _rows_count = collector.delete()
    2021-09-01T18:47:22.332989+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/db/models/deletion.py", line 435, in delete
    2021-09-01T18:47:22.332989+00:00 app[worker.1]: signals.post_delete.send(
    2021-09-01T18:47:22.332990+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/db/transaction.py", line 232, in __exit__
    2021-09-01T18:47:22.332990+00:00 app[worker.1]: connection.commit()
    2021-09-01T18:47:22.332990+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    2021-09-01T18:47:22.332991+00:00 app[worker.1]: return func(*args, **kwargs)
    2021-09-01T18:47:22.332991+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/db/backends/base/base.py", line 266, in commit
    2021-09-01T18:47:22.332991+00:00 app[worker.1]: self._commit()
    2021-09-01T18:47:22.332992+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    2021-09-01T18:47:22.332992+00:00 app[worker.1]: return self.connection.commit()
    2021-09-01T18:47:22.332992+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    2021-09-01T18:47:22.332993+00:00 app[worker.1]: raise dj_exc_value.with_traceback(traceback) from exc_value
    2021-09-01T18:47:22.332993+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/django/db/backends/base/base.py", line 242, in _commit
    2021-09-01T18:47:22.332993+00:00 app[worker.1]: return self.connection.commit()
    2021-09-01T18:47:22.332994+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/database_dbapi2.py", line 89, in commit
    2021-09-01T18:47:22.332994+00:00 app[worker.1]: return self.__wrapped__.commit()
    2021-09-01T18:47:22.332995+00:00 app[worker.1]: django.db.utils.IntegrityError: update or delete on table "websites_websitecontent" violates foreign key constraint "websites_websitecont_parent_id_3eb76791_fk_websites_" on table "websites_websitecontent"
    2021-09-01T18:47:22.332995+00:00 app[worker.1]: DETAIL:  Key (id)=(250589) is still referenced from table "websites_websitecontent".
    2021-09-01T18:47:22.332996+00:00 app[worker.1]:

**Comment by noisecapella** [comment]
If I set the chunk size to 10000, which means everything is in one chunk, then I don't see these errors
